//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SportsRelatedWebApplication.SoapWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SoapAPISoap", Namespace="http://tempuri.org/")]
    public partial class SoapAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RunningPaceCalculationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MileKmConversionOperationCompleted;
        
        private System.Threading.SendOrPostCallback HeartRateZoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback footballDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback footballFixtureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SoapAPI() {
            this.Url = global::SportsRelatedWebApplication.Properties.Settings.Default.SportsRelatedWebApplication_SoapWS_SoapAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RunningPaceCalculationCompletedEventHandler RunningPaceCalculationCompleted;
        
        /// <remarks/>
        public event MileKmConversionCompletedEventHandler MileKmConversionCompleted;
        
        /// <remarks/>
        public event HeartRateZoneCompletedEventHandler HeartRateZoneCompleted;
        
        /// <remarks/>
        public event footballDataCompletedEventHandler footballDataCompleted;
        
        /// <remarks/>
        public event footballFixtureCompletedEventHandler footballFixtureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RunningPaceCalculation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double RunningPaceCalculation(string type, double time, double distance, double pace) {
            object[] results = this.Invoke("RunningPaceCalculation", new object[] {
                        type,
                        time,
                        distance,
                        pace});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void RunningPaceCalculationAsync(string type, double time, double distance, double pace) {
            this.RunningPaceCalculationAsync(type, time, distance, pace, null);
        }
        
        /// <remarks/>
        public void RunningPaceCalculationAsync(string type, double time, double distance, double pace, object userState) {
            if ((this.RunningPaceCalculationOperationCompleted == null)) {
                this.RunningPaceCalculationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunningPaceCalculationOperationCompleted);
            }
            this.InvokeAsync("RunningPaceCalculation", new object[] {
                        type,
                        time,
                        distance,
                        pace}, this.RunningPaceCalculationOperationCompleted, userState);
        }
        
        private void OnRunningPaceCalculationOperationCompleted(object arg) {
            if ((this.RunningPaceCalculationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunningPaceCalculationCompleted(this, new RunningPaceCalculationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MileKmConversion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double MileKmConversion(string type, double distance) {
            object[] results = this.Invoke("MileKmConversion", new object[] {
                        type,
                        distance});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void MileKmConversionAsync(string type, double distance) {
            this.MileKmConversionAsync(type, distance, null);
        }
        
        /// <remarks/>
        public void MileKmConversionAsync(string type, double distance, object userState) {
            if ((this.MileKmConversionOperationCompleted == null)) {
                this.MileKmConversionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMileKmConversionOperationCompleted);
            }
            this.InvokeAsync("MileKmConversion", new object[] {
                        type,
                        distance}, this.MileKmConversionOperationCompleted, userState);
        }
        
        private void OnMileKmConversionOperationCompleted(object arg) {
            if ((this.MileKmConversionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MileKmConversionCompleted(this, new MileKmConversionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HeartRateZone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double HeartRateZone() {
            object[] results = this.Invoke("HeartRateZone", new object[0]);
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void HeartRateZoneAsync() {
            this.HeartRateZoneAsync(null);
        }
        
        /// <remarks/>
        public void HeartRateZoneAsync(object userState) {
            if ((this.HeartRateZoneOperationCompleted == null)) {
                this.HeartRateZoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHeartRateZoneOperationCompleted);
            }
            this.InvokeAsync("HeartRateZone", new object[0], this.HeartRateZoneOperationCompleted, userState);
        }
        
        private void OnHeartRateZoneOperationCompleted(object arg) {
            if ((this.HeartRateZoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HeartRateZoneCompleted(this, new HeartRateZoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/footballData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string footballData() {
            object[] results = this.Invoke("footballData", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void footballDataAsync() {
            this.footballDataAsync(null);
        }
        
        /// <remarks/>
        public void footballDataAsync(object userState) {
            if ((this.footballDataOperationCompleted == null)) {
                this.footballDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfootballDataOperationCompleted);
            }
            this.InvokeAsync("footballData", new object[0], this.footballDataOperationCompleted, userState);
        }
        
        private void OnfootballDataOperationCompleted(object arg) {
            if ((this.footballDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.footballDataCompleted(this, new footballDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/footballFixture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string footballFixture(string ID) {
            object[] results = this.Invoke("footballFixture", new object[] {
                        ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void footballFixtureAsync(string ID) {
            this.footballFixtureAsync(ID, null);
        }
        
        /// <remarks/>
        public void footballFixtureAsync(string ID, object userState) {
            if ((this.footballFixtureOperationCompleted == null)) {
                this.footballFixtureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfootballFixtureOperationCompleted);
            }
            this.InvokeAsync("footballFixture", new object[] {
                        ID}, this.footballFixtureOperationCompleted, userState);
        }
        
        private void OnfootballFixtureOperationCompleted(object arg) {
            if ((this.footballFixtureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.footballFixtureCompleted(this, new footballFixtureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RunningPaceCalculationCompletedEventHandler(object sender, RunningPaceCalculationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunningPaceCalculationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunningPaceCalculationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void MileKmConversionCompletedEventHandler(object sender, MileKmConversionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MileKmConversionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MileKmConversionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void HeartRateZoneCompletedEventHandler(object sender, HeartRateZoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeartRateZoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HeartRateZoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void footballDataCompletedEventHandler(object sender, footballDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class footballDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal footballDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void footballFixtureCompletedEventHandler(object sender, footballFixtureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class footballFixtureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal footballFixtureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591